version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./public:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
      - "22:22"
    restart: always
    container_name: nginx.local
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    volumes:
      - ./public:/public
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php_browscap.ini:/usr/local/etc/php/php_browscap.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database
    container_name: php
    expose:
      - "9003"
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password123'      
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - '/var/lib/mysql:/var/lib/mysql'
